services:
  docs:
    image: htmx_demo_local_docs
    container_name: htmx_demo_local_docs
    build:
      context: .
      dockerfile: ./compose/local/docs/Dockerfile
    env_file:
      - ./.envs/.local/.django
    volumes:
      - /app/.venv
      - ./docs:/docs:z
      - ./config:/app/config:z
      - ./htmx_demo:/app/htmx_demo:z
    ports:
      - '9000:9000'
    command: /start-docs
